# python-tests.yml
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black
        pip install .[test]
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 --count --show-source --statistics tests setup.py movienightbot
        # exit-zero treats all errors as warnings.
        flake8 --count --exit-zero --max-complexity=10 --statistics tests setup.py movienightbot
    - name: Lint with black
      run: |
        black --line-length 120 --check --diff --color tests setup.py movienightbot
#    - name: Test with pytest
#      run: |
#        python -m pytest
